resources:
  gpu: true

data:
  data_name: cifar10
  n: 60_000
  n_test: 1_000
  n_public: 2_000

models:
  architecture: VGG5 # also chosen for capc paper
  teacher_epochs: 200
  student_epochs: 200
  lr: 0.005
  weight_decay: 0.00005

pate:
  aggregators: ['confident']
  budgets:
    uGNMax:
    - [8, 16, 40]
    wGNMax:
    - [8, 16, 40]
  deltas: [1.0e-05]
  distributions:
  - 0: [0.34, 0.33, 0.33]
    1: [0.34, 0.33, 0.33]
    2: [0.34, 0.33, 0.33]
    3: [0.34, 0.33, 0.33]
    4: [0.34, 0.33, 0.33]
    5: [0.34, 0.33, 0.33]
    6: [0.34, 0.33, 0.33]
    7: [0.34, 0.33, 0.33]
    8: [0.34, 0.33, 0.33]
    9: [0.34, 0.33, 0.33]
  - 0: [0.8, 0.1, 0.1]
    1: [0.8, 0.1, 0.1]
    2: [0.8, 0.1, 0.1]
    3: [0.8, 0.1, 0.1]
    4: [0.8, 0.1, 0.1]
    5: [0.8, 0.1, 0.1]
    6: [0.8, 0.1, 0.1]
    7: [0.8, 0.1, 0.1]
    8: [0.8, 0.1, 0.1]
    9: [0.8, 0.1, 0.1]
  - 0: [0.1, 0.8, 0.1]
    1: [0.1, 0.8, 0.1]
    2: [0.1, 0.8, 0.1]
    3: [0.1, 0.8, 0.1]
    4: [0.1, 0.8, 0.1]
    5: [0.1, 0.8, 0.1]
    6: [0.1, 0.8, 0.1]
    7: [0.1, 0.8, 0.1]
    8: [0.1, 0.8, 0.1]
    9: [0.1, 0.8, 0.1]
  - 0: [0.1, 0.1, 0.8]
    1: [0.1, 0.1, 0.8]
    2: [0.1, 0.1, 0.8]
    3: [0.1, 0.1, 0.8]
    4: [0.1, 0.1, 0.8]
    5: [0.1, 0.1, 0.8]
    6: [0.1, 0.1, 0.8]
    7: [0.1, 0.1, 0.8]
    8: [0.1, 0.1, 0.8]
    9: [0.1, 0.1, 0.8]
  limits: ['budgets']
  n_labels: 500
  nums_teachers: [50]
  precision: 0.01
  seeds: [9]
  seeds2: [0, 1, 2, 3, 4]
  sigmas: [7] # from capc paper
  sigmas1: [26] # scaled to fit sigma
  ts: [35] # from capc paper

