resources:
  gpu: true

data:
  data_name: fashion_mnist
  n: 70000
  n_public: 9000
  n_test: 1000

models:
  architecture: VGG7
  lr: 0.0001
  student_epochs: 200
  teacher_epochs: 200
  weight_decay: 5.0e-05

pate:
  aggregators: [confident]
  budgets:
    GNMax:
    - [1]
  deltas: [1.0e-05]
  distributions:
  - 0: [1]
    1: [1]
    2: [1]
    3: [1]
    4: [1]
    5: [1]
    6: [1]
    7: [1]
    8: [1]
    9: [1]
  limits: [budgets]
  n_labels: 2000
  nums_teachers: [250]
  precision: 0.01
  seeds: [9]
  seeds2: [0, 1, 2, 3, 4]
  sigmas: [40]
  sigmas1: [150]
  ts: [200]
