resources:
  gpu: true

data:
  data_name: mnist
  n: 70000
  n_public: 9000
  n_test: 1000

models:
  architecture: VGG7
  lr: 0.001
  student_epochs: 10
  teacher_epochs: 60
  weight_decay: 5.0e-05

pate:
  aggregators: [confident]
  budgets:
    wGNMax: # upsampling
    - [1.0, 3.]
  deltas: [1.0e-05]
  distributions:
  - 0: [0.5, 0.5]
    1: [0.5, 0.5]
    2: [0.5, 0.5]
    3: [0.5, 0.5]
    4: [0.5, 0.5]
    5: [0.5, 0.5]
    6: [0.5, 0.5]
    7: [0.5, 0.5]
    8: [0.5, 0.5]
    9: [0.5, 0.5]

  limits: [budgets]
  n_labels: 2000
  nums_teachers: [250]
  precision: 0.01
  seeds: [9]
  seeds2: [0]
  sigmas: [40]
  sigmas1: [150]
  ts: [200]
